EMPTY = 0
BLACK = 1
WHITE = 2
DELETE_MATCH_TIMEOUT = 3600

BG_SLEEP_INTERVAL = 5
RESET_COUNT = 1000
REMOVE_MATCHES_COUNT = 1000
MOVE_TO_DB_COUNT = 100

WEBSITE_PATH = '/home/ixonstater/code/go/go_client/'
# WEBSITE_PATH = '/Users/otheruser/bin/lib/go-client'